<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>scala/xml/include/XIncludeException.scala</title>
        <script type="text/javascript" src="../../../linked.js"></script>
        <link rel="stylesheet" type="text/css" href="../../../style.css" title="Style">
    </head>
    <body onload="initializeLinked()">
        <pre>
<span class="comment">/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2002-2009, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |    http://scala-lang.org/               **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*                                                                      */</span>

<span class="comment">// $Id: XIncludeException.scala 16893 2009-01-13 13:09:22Z cunei $</span>

<span class="keyword">package</span> scala.xml.include

<span class="comment">/**
 * &lt;p&gt;
 * &lt;code&gt;XIncludeException&lt;/code&gt; is the generic superclass
 * for all checked exceptions that may be thrown as a result
 * of a violation of XInclude's rules.
 * &lt;/p&gt;
 * &lt;p&gt;
 * Constructs an &lt;code&gt;XIncludeException&lt;/code&gt; with the specified detail
 * message. The error message string &lt;code&gt;message&lt;/code&gt; can later be
 * retrieved by the &lt;code&gt;{@link java.lang.Throwable#getMessage}&lt;/code&gt;
 * method of class &lt;code&gt;java.lang.Throwable&lt;/code&gt;.
 * &lt;/p&gt;
 *
 * @param   message   the detail message.
 */</span>
<span class="keyword">class</span> <span class="typed"><span class="type">class XIncludeException extends java.lang.Exception with ScalaObject</span><a id="12278">XIncludeException</a></span>(<span class="typed"><span class="type">String</span><span id="67742"><a id="67753">message</a></span></span>: <span class="typed"><span class="type">String</span><a id="1859">String</a></span>) <span class="keyword">extends</span> <span class="typed"><span class="type">java.lang.Exception</span><a href="../../Predef.scala.html#13332" id="19899">Exception</a></span>(<span class="typed"><span class="type">String</span><a href="#67753">message</a></span>) {

  <span class="comment">/**
   * uses &lt;code&gt;null&lt;/code&gt; as its error detail message.
   */</span>
  <span class="keyword">def</span> <span class="typed"><span class="type">()scala.xml.include.XIncludeException</span><a id="67744" class="keyword">this</a></span>() = <span class="typed"><span class="type">XIncludeException.this.type</span><a href="#12278" class="keyword">this</a></span>(<span class="typed"><span class="type">Null(null)</span><span class="keyword">null</span></span>)

  <span class="keyword">private</span> <span class="keyword">var</span> <span class="typed"><span class="type">Throwable</span><span id="67747"><span id="67745"><span id="67746"><a id="67752">rootCause</a></span></span></span></span>: <span class="typed"><span class="type">Throwable</span><a id="2141">Throwable</a></span> = <span class="typed"><span class="type">Null(null)</span><span class="keyword">null</span></span>

  <span class="comment">/**
   * When an &lt;code&gt;IOException&lt;/code&gt;, &lt;code&gt;MalformedURLException&lt;/code&gt; 
   * or other generic exception is thrown while processing an XML document
   * for XIncludes, it is customarily replaced
   * by some form of &lt;code&gt;XIncludeException&lt;/code&gt;.  
   * This method allows you to store the original exception.
   *
   * @param   nestedException   the underlying exception which 
   caused the XIncludeException to be thrown
   */</span>
  <span class="keyword">def</span> <span class="typed"><span class="type">(Throwable)Unit</span><a id="67748">setRootCause</a></span>(<span class="typed"><span class="type">Throwable</span><a id="67762">nestedException</a></span>: <span class="typed"><span class="type">Throwable</span><a id="2141">Throwable</a></span> ) {
    <span class="typed"><span class="type">XIncludeException.this.type</span><a href="#12278" class="keyword">this</a></span>.<span class="typed"><span class="type">(Throwable)Unit</span><a href="#67746">rootCause</a></span> = <span class="typed"><span class="type">Throwable</span><a href="#67762">nestedException</a></span>
  }

  <span class="comment">/**
   * When an &lt;code&gt;IOException&lt;/code&gt;, &lt;code&gt;MalformedURLException&lt;/code&gt; 
   * or other generic exception is thrown while processing an XML document
   * for XIncludes, it is customarily replaced
   * by some form of &lt;code&gt;XIncludeException&lt;/code&gt;.  
   * This method allows you to retrieve the original exception.
   * It returns null if no such exception caused this &lt;code&gt;XIncludeException&lt;/code&gt;.
   *
   * @return Throwable   the underlying exception which caused the
   *                     &lt;code&gt;XIncludeException&lt;/code&gt; to be thrown
   */</span>
  <span class="keyword">def</span> <span class="typed"><span class="type">()Throwable</span><a id="67749">getRootCause</a></span>(): <span class="typed"><span class="type">Throwable</span><a id="2141">Throwable</a></span> = <span class="typed"><span class="type">XIncludeException.this.type</span><a href="#12278" class="keyword">this</a></span>.<span class="typed"><span class="type">=&gt; Throwable</span><a href="#67745">rootCause</a></span>
  
}

        </pre>
    </body>
</html>