<?xml version="1.0" encoding="utf-8"?>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>xml/include/XIncludeException.scala</title>
        <script type="text/javascript" src="../../jquery-all.js"></script>
        <script type="text/javascript" src="../../linked.js"></script>
        <link rel="stylesheet" type="text/css" href="../../style.css" title="Style">
    </head>
    <body>
        <pre>
/*                     __                                               *\
**     ________ ___   / /  ___     Scala API                            **
**    / __/ __// _ | / /  / _ |    (c) 2002-2009, LAMP/EPFL             **
**  __\ \/ /__/ __ |/ /__/ __ |    http://scala-lang.org/               **
** /____/\___/_/ |_/____/_/ | |                                         **
**                          |/                                          **
\*                                                                      */

// $Id: XIncludeException.scala 18387 2009-07-24 15:28:37Z odersky $

<span class="keyword">package</span> scala.xml
<span class="keyword">package</span> include

/**
 * &lt;p&gt;
 * &lt;code&gt;XIncludeException&lt;/code&gt; is the generic superclass
 * for all checked exceptions that may be thrown as a result
 * of a violation of XInclude's rules.
 * &lt;/p&gt;
 * &lt;p&gt;
 * Constructs an &lt;code&gt;XIncludeException&lt;/code&gt; with the specified detail
 * message. The error message string &lt;code&gt;message&lt;/code&gt; can later be
 * retrieved by the &lt;code&gt;{@link java.lang.Throwable#getMessage}&lt;/code&gt;
 * method of class &lt;code&gt;java.lang.Throwable&lt;/code&gt;.
 * &lt;/p&gt;
 *
 * @param   message   the detail message.
 */
<span class="keyword">class</span> <a title="class XIncludeException extends java.lang.Exception with ScalaObject" id="9886">XIncludeException</a><a href="../../ScalaObject.scala.html#957" title="ScalaObject" id="19679">(</a><a title="String" id="83577">message</a>: <a title="String" id="1603">String</a>) <span class="keyword">extends</span> <a href="../../Predef.scala.html#16161" title="java.lang.Exception">Exception</a>(<a href="#83577" title="String">message</a>) {

  /**
   * uses &lt;code&gt;null&lt;/code&gt; as its error detail message.
   */
  <span class="keyword">def</span> <a title="()scala.xml.include.XIncludeException" id="83561" class="keyword">this</a>() = <a href="#9886" title="XIncludeException.this.type" class="keyword">this</a>(<span title="Null(null)" class="keyword">null</span>)

  <span class="keyword">private</span> <span class="keyword">var</span> <a title="Throwable" id="83563">rootCause</a>: <span title="Throwable">Throwable</span> = <span title="Null(null)" class="keyword">null</span>

  /**
   * When an &lt;code&gt;IOException&lt;/code&gt;, &lt;code&gt;MalformedURLException&lt;/code&gt; 
   * or other generic exception is thrown while processing an XML document
   * for XIncludes, it is customarily replaced
   * by some form of &lt;code&gt;XIncludeException&lt;/code&gt;.  
   * This method allows you to store the original exception.
   *
   * @param   nestedException   the underlying exception which 
   caused the XIncludeException to be thrown
   */
  <span class="keyword">def</span> <a title="(nestedException: Throwable)Unit" id="83565">setRootCause</a>(<a title="Throwable" id="213932">nestedException</a>: <span title="Throwable">Throwable</span> ) {
    <a href="#9886" title="XIncludeException.this.type" class="keyword">this</a>.<a href="#83563" title="(x$1: Throwable)Unit">rootCause</a> = <a href="#213932" title="Throwable">nestedException</a>
  }

  /**
   * When an &lt;code&gt;IOException&lt;/code&gt;, &lt;code&gt;MalformedURLException&lt;/code&gt; 
   * or other generic exception is thrown while processing an XML document
   * for XIncludes, it is customarily replaced
   * by some form of &lt;code&gt;XIncludeException&lt;/code&gt;.  
   * This method allows you to retrieve the original exception.
   * It returns null if no such exception caused this &lt;code&gt;XIncludeException&lt;/code&gt;.
   *
   * @return Throwable   the underlying exception which caused the
   *                     &lt;code&gt;XIncludeException&lt;/code&gt; to be thrown
   */
  <span class="keyword">def</span> <a title="()Throwable" id="83566">getRootCause</a>(): <span title="Throwable">Throwable</span> = <a href="#9886" title="XIncludeException.this.type" class="keyword">this</a>.<a href="#83563" title="=&gt; Throwable">rootCause</a>
  
}

        </pre>
    </body>
</html>